### ISSUE TITLE
Rework cpu init paths to use ppc_md.flush_tlb()

### ISSUE THREAD

**Issue by mpe** [linuxppc/linux#15]
Currently the various cpu setup routines all do their own TLB flush. Now that we have `ppc_md.flush_tlb()`we should be able to use that to do the TLB flush in one place.

**Comment by npiggin** [comment]
This description is obsolete after d4748276ae14 ("powerpc/64s: Improve local TLB flush for boot and MCE on POWER9").

However the CPU setup routines could implement tlb flushing similarly with inline asm and call it early_init_mmu, I think.

**Comment by deece** [comment]
Still relevant

**Comment by mpe** [comment]
I'll close this and call it fixed in d474827, if we want to rework things further we can do that separately.
