### ISSUE TITLE
lib/test-hexdump.c doesn't work on BE

### ISSUE THREAD

**Issue by mpe** [linuxppc/linux#16]

**Comment by mikey** [comment]
+1

**Comment by chleroy** [comment]
Proposed patch: https://patchwork.ozlabs.org/patch/954794/

**Comment by chleroy** [comment]
Patch merged
Commit de9df3993cfffde468c1c226382f24cec7e9fedc ("lib/test_hexdump.c: fix failure on big endian cpu")

**Comment by mpe** [comment]
Thanks @chleroy :champagne:
