### ISSUE TITLE
Module auto load based on CPU features

### ISSUE THREAD

**Issue by antonblanchard** [linuxppc/linux#20]
x86 can automatically load modules based on CPU features via MODULE_DEVICE_TABLE(x86cpu, ...)

We'd like similar functionality on powerpc. One example is the POWER8 CRC32 - without automatic loading we will just use the default slow routines unless someone specifically loads the module.

**Comment by mpe** [comment]
Looks like we want to implement CONFIG_GENERIC_CPU_AUTOPROBE.

See eg. 3be1a5c4f75989cf457f13f38ff0913dff6d4996 for the arm64 support.

**Comment by antonblanchard** [comment]
Nice! I found another case of this with vmx_crypto

**Comment by mpe** [comment]
Implemented by @deece in 4a1202765ddf4e5bb3143c0a859ee37f8fcf9b85.
