### ISSUE TITLE
Clean up tm_abort duplication in hash_utils_64.c

### ISSUE THREAD

**Issue by mpe** [linuxppc/linux#23]
The same logic appears twice and should probably be pulled out into a function.

**Comment by tengrui** [comment]
Patch for the tm_abort duplication problem:
https://lkml.org/lkml/2016/8/26/78

**Comment by tengrui** [comment]
Fixed in https://github.com/linuxppc/linux/commit/f1a55ce0544251746d9b52fb85ad32f31a43fbd2.

**Comment by mpe** [comment]
Thanks @tengrui !
