### ISSUE TITLE
xmon: ignore control characters

### ISSUE THREAD

**Issue by ajdlinux** [linuxppc/linux#31]
```
Unrecognized command: \x1b[B\x1b[B\x1b[B\x1b[B\x1b[B\x1b[B\x1b[B\x1b[B\x1b[B\x1b[B\x1b[B\x1b[B\x1b[B\x1b[B\x1b[B\x1b[B\x1b[B\x1b[Be (type ? for help)
```

This is what happens when xmon sees me scroll my mouse wheel...

**Comment by mpe** [comment]
:mouse: :gun:

**Comment by ajdlinux** [comment]
I'm happy to take this

**Comment by deece** [comment]
@ajdlinux Is this still relevant?

**Comment by mpe** [comment]
We'd still want to print at least the first character, not just ignore it silently, in case your console is sending bad characters or something. So it's probably not worth making the code more complex just to suppress printing the rest of the characters.
