### ISSUE TITLE
Convert asm to use .8byte instead of .llong

### ISSUE THREAD

**Issue by mpe** [linuxppc/linux#33]
`.llong` is an undocumented PPC specific directive. The generic equivalent is `.quad`, but even better (because it's self describing) is the (currently undocumented) `.8byte`.

We should try to switch over to `.8byte`, though it's not high priority so we'll want to make sure it doesn't interfere with any other work.

We should also try and get binutils to document `.8byte` and the other explicitly sized directives.

**Comment by antonblanchard** [comment]
I recently found .4byte, .8byte etc which are clearer to me. I also prefer to use .balign instead of .align.

**Comment by mpe** [comment]
Ah nice. Are they documented somewhere?

**Comment by antonblanchard** [comment]
Unfortunately not. I spoke to Alan and the gas docs should document them under the generic pseudo ops section. Right now ARM and nios2 incorrectly defines them as arch specific.

**Comment by csmart** [comment]
so should we be replacing .llong with .8byte?

**Comment by mpe** [comment]
I guess, part of the motivation for using `.quad` was that it's documented. But I think Anton's right that `.8byte` is better as it's more explicit. Who wants to do a gas patch to document them?

**Comment by tcharding** [comment]
.8byte is not used anywhere else in the tree except for one time (arch/alpha/include/asm/bug.h:14). Does that matter?

**Comment by mpe** [comment]
@tcharding that's a good point, but I think it's just a symptom of `.8byte` not being documented (which should be fixed in binutils).

So I think we can start using `.8byte` etc. and although it might be new to people, it's fairly obvious what it does given the name, and hopefully it will eventually be documented as well.

**Comment by tcharding** [comment]
Have submitted a patch to the binutils mailing list to add documentation for .Nbyte assembler directives.

Subject: [PATCH] Document .Nbyte assembler directives

Have never worked on binutils before so may well take some rework before this is able to be accepted.

**Comment by tcharding** [comment]
Documentation is in the binutils-gdb tree

+2017-03-07  Tobin C. Harding  <me@tobin.cc>
+           Alan Modra  <amodra@gmail.com>
+
+       * doc/as.texinfo (2byte, 4byte, 8byte): Document.
+       * doc/c-arm.texi (2byte, 4byte, 8byte): Omit if ELF.
+

converting .llong to .8byte is a perl oneliner + testing, is it not? My *cough* test infrastructure is no doubt less capable than yours but I'm happy to put a patch in with it if you would like me to.

**Comment by mpe** [comment]
Great work on the binutils patch, you have one more binutils patch committed than me :+1: 

Yeah doing the conversion is just a **python** one liner :wink: and some testing. 

I actually only see 38 `.llong`'s, unless I'm grepping badly. So we could probably just do that as one patch.

If you're happy to do the patch and post it to the list that'd be great, I can crank it through my CI infrastructure and check it works.

**Comment by mpe** [comment]
Fixed in eb039161da2ff388cc30d076badd8e, thanks @tcharding :beer:
