### ISSUE TITLE
Add support for more compression methods to zImage wrapper

### ISSUE THREAD

**Issue by mpe** [linuxppc/linux#35]
The powerpc zImage wrapper only supports compressing the kernel with gzip. It would be nice to support some of the other methods, which have different speed/size trade offs.

The actual compression algorithms _should_ be reusable from the library code. For example the x86 wrapper code does:

`arch/x86/boot/compressed/misc.c:#include "../../../../lib/decompress_unxz.c"`

**Comment by ruscur** [comment]
Working on this, will update if I succeed...or any findings if I fail

**Comment by shenki** [comment]
I attempted this a while back. Ping me @ruscur and I'll show you what I had

**Comment by ruscur** [comment]
Got xz working with space savings of around 30%, but it's hacky.  Working on other algorithms and making it upstreamable.

@shenki, I believe @oohal pinged you with our current progress

**Comment by ruscur** [comment]
Making this work properly has required a lot of changes to the boot wrapper, which @oohal has overhauled significantly.  Hence, any and all boot wrapper issues are now his problem.

**Comment by stewart-ibm** [comment]
@oohal any progress here?

**Comment by oohal** [comment]
I'm not overly happy with the implementation but it does work (for me). I'll rebase it on 4.8 and post it to the list.

**Comment by stewart-ibm** [comment]
Works with 4.9, so we can probably close this issue.

**Comment by mpe** [comment]
Yep, implemented in c762c69e106f, thanks all.
