### ISSUE TITLE
Use ifdef instead of ifeq in Makefiles

### ISSUE THREAD

**Issue by mpe** [linuxppc/linux#36]
A lot of our `Makefile`s have:

```
ifeq ($(CONFIG_FOO),y)
```

But for boolean symbols we can just do:

```
ifdef CONFIG_FOO
```

The latter reads much easier, and we should convert to it whenever possible.

Note if the symbol is a tristate (ie. potentially a module), and you need to test that symbol is 'y' and not 'm' then you still need the `ifeq` syntax.

**Comment by mopsfelder** [comment]
Rodrigo sent the fix to lkml:

http://patchwork.ozlabs.org/patch/953986/

**Comment by mopsfelder** [comment]
Applied to powerpc next:

https://git.kernel.org/powerpc/c/badf436f6fa5dc864d579d73fe7538

**Comment by mpe** [comment]
Implemented in badf436f6fa5dc864d579d73fe7538, thanks @rrosatti :beers:

**Comment by rrosatti** [comment]
You're welcome @mpe \o/ :coffee:
