### ISSUE TITLE
Remove #ifdef CONFIG_SMP from smp_send_stop() calls

### ISSUE THREAD

**Issue by mpe** [linuxppc/linux#40]
We have a few calls to `smp_send_stop()` in `setup-common.c` which are inside `#ifdef CONFIG_SMP`.

The `#ifdef` should not be necessary, as there is an empty version of `smp_send_stop()` defined in `include/linux/smp.h`.

**Comment by csmart** [comment]
Patch sent to mailing list, http://patchwork.ozlabs.org/patch/617372/

**Comment by mpe** [comment]
Fixed in 44bd82e613778f5de3fad11ed752e2e5ae8d2f92.
