### ISSUE TITLE
Check/remove suspect CONFIG_PPC_BOOK3E #ifdefs in nohash/64/pgtable.h

### ISSUE THREAD

**Issue by mpe** [linuxppc/linux#46]
There are three `#ifdef CONFIG_PPC_BOOK3E` sections in `nohash/64/pgtable.h`.

AIUI there _should_ be no configurations possible which use `nohash/64/pgtable.h` but don't also enable `CONFIG_PPC_BOOK3E`.

**Comment by tengrui** [comment]
https://lkml.org/lkml/2016/8/25/82

I checked following code, and 'nohash' is only used for BOOK3E, so it does not need to suspect CONFIG_PPC_BOOK3E in nohash/64/pgtable.h.
#ifdef CONFIG_PPC_BOOK3S
#include <asm/book3s/pgtable.h>
#else
#include <asm/nohash/pgtable.h>
#endif /* !CONFIG_PPC_BOOK3S */

**Comment by mpe** [comment]
Fixed in fda0440d82d3, thanks @tengrui :beers:
