### ISSUE TITLE
Move struct hcall_stats into hvCall_inst.c

### ISSUE THREAD

**Issue by mpe** [linuxppc/linux#54]
`struct hcall_stats` is only used in `hvCall_inst.c`, move it there.

**Comment by csmart** [comment]
is this also not used in arch/powerpc/kernel/asm-offsets.c?

**Comment by mpe** [comment]
Those usages have been removed in next, see aac6a91fea.

**Comment by mpe** [comment]
Fixed in 017614a5d6c0, thanks @tcharding :cake:
