### ISSUE TITLE
Add Anton's null_syscall benchmark to the selftests

### ISSUE THREAD

**Issue by mpe** [linuxppc/linux#68]
Pull in a version of Anton's `null_syscall` benchmark:

http://ozlabs.org/~anton/junkcode/null_syscall.c

Into `tools/testing/selftests/powerpc/benchmarks`.

**Comment by tengrui** [comment]
https://lkml.org/lkml/2016/9/23/104

**Comment by mpe** [comment]
Fixed in d8db9bc55a31. Thanks @tengrui
