### ISSUE TITLE
lib/crc32.c - crc32c hardware suppot

### ISSUE THREAD

**Issue by grooverdan** [linuxppc/linux#70]
Using the mechanism d2cf5be07ff7c7cde8bef8551a30e8e86e2037a7 is it possible to use [crc32c_vpmsum_init](https://github.com/linuxppc/linux/blob/next/arch/powerpc/crypto/crc32c-vpmsum_glue.c#L78) to replace the generic [__crc32c_le](https://github.com/linuxppc/linux/blob/next/lib/crc32.c#L199) to [__crc32c_vpmsum](https://github.com/linuxppc/linux/blob/next/arch/powerpc/crypto/crc32c-vpmsum_asm.S#L894)?

During high IO load on XFS this is rather evident (fs/xfs/xfs_log.c#L1662)

<pre>
-   11.90%  hdlatency        [kernel.kallsyms]        [k] __crc32c_le                                                                                             ▒
     0                                                                                                                                                            ▒
     __libc_start_main                                                                                                                                            ▒
     0x2319c                                                                                                                                                      ▒
     main                                                                                                                                                         ▒
     run_random_all                                                                                                                                               ▒
     run_random_one                                                                                                                                               ▒
     fsync                                                                                                                                                        ▒
     system_call                                                                                                                                                  ▒
     sys_fsync                                                                                                                                                    ▒
     do_fsync                                                                                                                                                     ▒
     vfs_fsync_range                                                                                                                                              ▒
     xfs_file_fsync                                                                                                                                               ▒
     _xfs_log_force_lsn                                                                                                                                           ▒
   - xlog_sync                                                                                                                                                    ▒
      - 11.90% xlog_cksum                                                                                                                                         ▒
         - 11.89% crc32c                                                                                                                                          ▒
            - 11.89% crypto_shash_update                                                                                                                          ▒
               - 11.89% chksum_update                                                                                                                             ▒
                    __crc32c_le                                                                                                                                   ▒
                 0.00% __crc32c_le                                                                                                                                ▒
              0.00% __crc32c_le                                                                                                                                   ▒
            + 0.00% chksum_update                                                                                                                                 ▒
           0.01% __crc32c_le                                                                                                                                      ▒
         + 0.00% crypto_shash_update                                                                                                                              ▒
      - 0.00% 0                                                                                                                                                   ▒
           xlog_cksum                                                                                                                                             ▒
           __crc32c_le                                                                                                                                            ▒
      - 0.00% crc32c                                                                                                                                              ▒
           __crc32c_le                                                                                                                                            ▒</pre>

**Comment by grooverdan** [comment]
http://www.gossamer-threads.com/lists/linux/kernel/956020#956020 seemed this didn't progress far.

**Comment by npiggin** [comment]
It should work automatically, but I think xfs is doing crcs on a bunch of 260 byte headers, so they'll never get past VECTOR_BREAKPOINT. However in this case if it's doing a lot headers, it might be worth the cost, I'm not sure. Try reducing VECTOR_BREAKPOINT to something small like VMX_ALIGN and see what performance is like.

**Comment by npiggin** [comment]
Daniel got a profile on current kernel where crc32c is still not being vectorized. Possibly due to vector breakpoint issue. We'll have to do some experiments and see what XFS is doing exactly (it's checksumming looks fairly painful).

1.11%  mysqld           [kernel.vmlinux]            [k] __crc32c_le
            |
            ---__crc32c_le
               |          
                --1.11%--chksum_update
                          |          
                           --1.11%--crypto_shash_update
                                     crc32c
                                     xlog_cksum
                                     xlog_sync
                                     _xfs_log_force_lsn
                                     xfs_file_fsync
                                     vfs_fsync_range
                                     do_fsync
                                     sys_fsync
                                     system_call
                                     0x17738
                                     0x17704
                                     os_file_flush_func
                                     fil_flush

**Comment by grooverdan** [comment]
resolved per https://patchwork.ozlabs.org/patch/690349/
