### ISSUE TITLE
VGA support - pseries_le - 4.9.0-rc2 - fails to boot

### ISSUE THREAD

**Issue by grooverdan** [linuxppc/linux#77]
pseries_le_defconfig compiled kernel in qemu with VGA enabled, shows the cpu representations of Tux and with no other output reboots within 10 seconds.

**Comment by mpe** [comment]
I know there have been problems with LE & Qemu VGA in the past, I'm not sure if those are all fixed yet. @ozbenh was working on it a while back and might be able to tell us if it's expected to work.

**Comment by ozbenh** [comment]
If you see tux I'm not sure it's a fb problem. Travelling now but can you see if there's something on the hvc/serial console ?

**Comment by grooverdan** [comment]
<pre>
qemu-later/bin/qemu-system-ppc64 -enable-kvm -name vga-bug-disect-machine -machine pseries,accel=kvm,usb=off -m 10240 -realtime mlock=off -smp 20,sockets=20,cores=1,threads=1 -uuid e43226ee-bdc1-4150-92c2-ffcf6ff2d647 -rtc base=utc -no-shutdown -boot menu=off,strict=on -device pci-ohci,id=usb,bus=pci.0,addr=0x2 -device usb-kbd,id=input0 -device usb-mouse,id=input1  -device virtio-balloon-pci,id=balloon0,bus=pci.0,addr=0x4 -msg timestamp=on  -vnc 127.0.0.1:0 -device VGA,id=video0,vgamem_mb=16,bus=pci.0,addr=0x5  -kernel linux/vmlinux -nographic
</pre>

Last output before the reboot on the console was `#1 SMT {date}`
<pre>
Scanning USB 
  OHCI: initializing
    USB Keyboard 
    USB mouse 
No console specified using screen & keyboard
     ted RAM kernel at 400000 (f2976c bytes) C08FF
  Welcome to Open Firmware

  Copyright (c) 2004, 2011 IBM Corporation All rights reserved.
  This program and the accompanying materials are made available
  under the terms of the BSD License available at
  http://www.opensource.org/licenses/bsd-license.php

Booting from memory...
Linux ppc64le
#1 SMP Mon Oct 3

SLOF **********************************************************************
QEMU Starting
</pre>

Changing to 
<pre>
qemu-later/bin/qemu-system-ppc64 -enable-kvm -name vga-bug-disect-machine -machine pseries,accel=kvm,usb=off -m 10240 -realtime mlock=off -smp 20,sockets=20,cores=1,threads=1 -uuid e43226ee-bdc1-4150-92c2-ffcf6ff2d647 -rtc base=utc -no-shutdown -boot menu=off,strict=on -device pci-ohci,id=usb,bus=pci.0,addr=0x2 -device usb-kbd,id=input0 -device usb-mouse,id=input1  -device virtio-balloon-pci,id=balloon0,bus=pci.0,addr=0x4 -msg timestamp=on    -kernel linux/vmlinux   -vga none -nographic
</pre>

Git bisected problem to 05fd007e46296afb24d15c7d589d535e5a5b9d5c

**Comment by grooverdan** [comment]
validated with kernel at 2a26d99b251b8625d27aed14e97fc10707a3a81f failing to boot and the same kernel with 05fd007e46296afb24d15c7d589d535e5a5b9d5c reverted is booting ok on ppc64le/qemu. These kernels are started via grub.

test env:
<pre>
ozlabs@fstn4:~$ killall qemu-system-ppc64 ; sleep 1 ;qemu-later/bin/qemu-system-ppc64 -enable-kvm -name vga-bug-disect-machine -machine pseries,accel=kvm,usb=off -m 10240 -realtime mlock=off -smp 20,sockets=20,cores=1,threads=1 -uuid e43226ee-bdc1-4150-92c2-ffcf6ff2d647 -rtc base=utc -no-shutdown -boot menu=off,strict=on -device pci-ohci,id=usb,bus=pci.0,addr=0x2 -device usb-kbd,id=input0 -device usb-mouse,id=input1  -device virtio-balloon-pci,id=balloon0,bus=pci.0,addr=0x4 -msg timestamp=on  -vnc 127.0.0.1:10   -kernel  vmlinux-4.9-rc3-2a26d99b251b8625d27aed14e97fc10707a3a81f & (sleep 3.1; vncviewer :10)
</pre>

**Comment by mpe** [comment]
Yep I see that too.

The qemu command line can be much simpler, just:

`qemu-system-ppc64 -M pseries -m 1G  -kernel vmlinux`

Is enough to trigger the bug.

**Comment by grooverdan** [comment]
Thread: https://lists.ozlabs.org/pipermail/linuxppc-dev/2016-October/thread.html#149820 / http://marc.info/?t=147678252000003&r=1&w=2

**Comment by grooverdan** [comment]
Appears headed for revert - https://patchwork.ozlabs.org/patch/690349/
