### ISSUE TITLE
Implement csum_ipv6_magic() in asm

### ISSUE THREAD

**Issue by mpe** [linuxppc/linux#9]
Assuming it's faster of course :smiley_cat: 

And `#define _HAVE_ARCH_IPV6_CSUM`.

**Comment by chleroy** [comment]
v3 implements it for both PPC32 and PPC64 https://patchwork.ozlabs.org/patch/918032/

**Comment by chleroy** [comment]
Sure, was tested on PPC32 (8xx) with the following app. Should be possible to use in PPC64 as is I believe

`
#include <stdlib.h>
#include <unistd.h>
#include <stdio.h>
#include <time.h>
#include <arpa/inet.h>
#include <netinet/in.h>

#define __sum16	unsigned short
#define __u32 unsigned int
#define u32 unsigned int
#define __u8 unsigned char
#define __wsum unsigned int
#define __force

static inline __sum16 csum_fold(__wsum csum)
{
	u32 sum = (__force u32)csum;
	sum = (sum & 0xffff) + (sum >> 16);
	sum = (sum & 0xffff) + (sum >> 16);
	return (__force __sum16)~sum;
}

__sum16 csum_ipv6_magic(const struct in6_addr *saddr,
			const struct in6_addr *daddr,
			__u32 len, __u8 proto, __wsum csum);

static __sum16 csum_ipv6_magic_gen(const struct in6_addr *saddr,
			const struct in6_addr *daddr,
			__u32 len, __u8 proto, __wsum csum)
{

	int carry;
	__u32 ulen;
	__u32 uproto;
	__u32 sum = (__force u32)csum;

	sum += (__force u32)saddr->s6_addr32[0];
	carry = (sum < (__force u32)saddr->s6_addr32[0]);
	sum += carry;

	sum += (__force u32)saddr->s6_addr32[1];
	carry = (sum < (__force u32)saddr->s6_addr32[1]);
	sum += carry;

	sum += (__force u32)saddr->s6_addr32[2];
	carry = (sum < (__force u32)saddr->s6_addr32[2]);
	sum += carry;

	sum += (__force u32)saddr->s6_addr32[3];
	carry = (sum < (__force u32)saddr->s6_addr32[3]);
	sum += carry;

	sum += (__force u32)daddr->s6_addr32[0];
	carry = (sum < (__force u32)daddr->s6_addr32[0]);
	sum += carry;

	sum += (__force u32)daddr->s6_addr32[1];
	carry = (sum < (__force u32)daddr->s6_addr32[1]);
	sum += carry;

	sum += (__force u32)daddr->s6_addr32[2];
	carry = (sum < (__force u32)daddr->s6_addr32[2]);
	sum += carry;

	sum += (__force u32)daddr->s6_addr32[3];
	carry = (sum < (__force u32)daddr->s6_addr32[3]);
	sum += carry;

	ulen = (__force u32)htonl((__u32) len);
	sum += ulen;
	carry = (sum < ulen);
	sum += carry;

	uproto = (__force u32)htonl(proto);
	sum += uproto;
	carry = (sum < uproto);
	sum += carry;

	return csum_fold((__force __wsum)sum);
}

int main(int argc, char **argv)
{
	int i;

	srand(time(NULL));

	for (i = 0; i < 1000000; i++) {
		struct in6_addr saddr, daddr;
		unsigned int len, csum;
		unsigned char proto;
		int j;
		unsigned short sum0, sum;

		for (j = 0; j < 4; j++) {
			saddr.s6_addr32[j] = rand();
			daddr.s6_addr32[j] = rand();
		}
		len = rand();
		proto = rand();
		csum = rand();
		
		sum0 = csum_ipv6_magic_gen(&saddr, &daddr, len, proto, csum);
		sum = csum_ipv6_magic(&saddr, &daddr, len, proto, csum);
		if (sum0 != sum) {
			char sstr[INET6_ADDRSTRLEN];
			char dstr[INET6_ADDRSTRLEN];

			inet_ntop(AF_INET6, &saddr, sstr, sizeof(sstr));
			inet_ntop(AF_INET6, &daddr, dstr, sizeof(dstr));
			printf("WRONG SUM %s %s %u %u %u ==> %x != %x\n", sstr, dstr, len, proto, csum, sum0, sum);
		}
	}
}
`

**Comment by chleroy** [comment]
Implementation done, see commit e9c4943a107b5 ("powerpc: Implement csum_ipv6_magic in assembly")

**Comment by mpe** [comment]
Thanks @chleroy :champagne:
