### ISSUE TITLE
Investigate/fix randconfig failures

### ISSUE THREAD

**Issue by mpe** [linuxppc/linux#94]
Not all `randconfig` failures are due to powerpc code, but some are (or probably are):

- ~~http://kisskb.ellerman.id.au/kisskb/buildresult/13052890/ (`link-vmlinux.sh: line 80: 13095 Segmentation fault`~~
- ~~http://kisskb.ellerman.id.au/kisskb/buildresult/12982152/~~
- ~~http://kisskb.ellerman.id.au/kisskb/buildresult/12982362/~~

To fix, download the config from one of the results above, reproduce the failure on mainline, work out what the problem is.

**Comment by mopsfelder** [comment]
@mpe I sent a patch to lkml for the first build issue:

https://www.spinics.net/lists/kernel/msg2518373.html

**Comment by mopsfelder** [comment]
The second build error is because `drivers/vfio/pci/vfio_pci.c` depends on symbols (`vfio_spapr_pci_eeh_release` and `vfio_spapr_pci_eeh_open`) defined in `drivers/vfio/vfio_spapr_eeh.c` but `CONFIG_VFIO_SPAPR_EEH` is not defined.

Selecting `CONFIG_VFIO_SPAPR_EEH` in `CONFIG_VFIO_PCI` fixes the build:

```diff
diff --git a/drivers/vfio/pci/Kconfig b/drivers/vfio/pci/Kconfig
index 24ee260..ec73ccb 100644
--- a/drivers/vfio/pci/Kconfig
+++ b/drivers/vfio/pci/Kconfig
@@ -1,6 +1,7 @@
 config VFIO_PCI
        tristate "VFIO support for PCI devices"
        depends on VFIO && PCI && EVENTFD
+       select VFIO_SPAPR_EEH
        select VFIO_VIRQFD
        select IRQ_BYPASS_MANAGER
        help
```

But the following warning message appears:

```
warning: (VFIO_PCI) selects VFIO_SPAPR_EEH which has unmet direct dependencies (EEH && VFIO_IOMMU_SPAPR_TCE)
warning: (VFIO_PCI) selects VFIO_SPAPR_EEH which has unmet direct dependencies (EEH && VFIO_IOMMU_SPAPR_TCE)
```

Should `CONFIG_EEH` and `CONFIG_VFIO_IOMMU_SPAPR_TCE` also be selected in `CONFIG_VFIO_PCI` to satisfy `CONFIG_SPAPR_EEH` dependencies?

Another possible approach can be factoring out these symbols to somewhere else and make sure `vfio_pci.c` and `vfio_spapr_eeh.c` include them.  In this case, where these symbols should live?

@mpe I'd like your input here. Then, I can send a patch.

**Comment by mpe** [comment]
@mopsfelder `vfio_pci.c` is not powerpc-specific, so it should not depend on powerpc-only Kconfig symbols.

It should be using the empty definitions of those functions in `include/linux/vfio.h`.

I think the problem is those definitions are guarded by `CONFIG_EEH`, but it's possible to have `CONFIG_EEH=y` but `CONFIG_VFIO_SPAPR_EEH=n`. So the fix I think is to change the `#ifdef` in `vfio.h` to use `CONFIG_VFIO_SPAPR_EEH` not `CONFIG_EEH`.

**Comment by mopsfelder** [comment]
@mpe Thanks for the explanation. What do you think about the following commit (any comment on the commit message or anything else)? Does it sound reasonable to send upstream?

```diff
include/linux/vfio.h: Guard powerpc-specific functions with CONFIG_VFIO_SPAPR_EEH

When CONFIG_EEH=y and CONFIG_VFIO_SPAPR_EEH=n, build fails with the
following:

    drivers/vfio/pci/vfio_pci.o: In function `.vfio_pci_release':
    vfio_pci.c:(.text+0xa98): undefined reference to `.vfio_spapr_pci_eeh_release'
    drivers/vfio/pci/vfio_pci.o: In function `.vfio_pci_open':
    vfio_pci.c:(.text+0x1420): undefined reference to `.vfio_spapr_pci_eeh_open'

In this case, vfio_pci.c should use the empty definitions of
vfio_spapr_pci_eeh_open and vfio_spapr_pci_eeh_release functions.

This patch fixes it by guarding these function definitions with
CONFIG_VFIO_SPAPR_EEH.

This issue was found during a randconfig build. Logs are here:

    http://kisskb.ellerman.id.au/kisskb/buildresult/12982362/

Signed-off-by: Murilo Opsfelder Araujo <mopsfelder@gmail.com>
---
 include/linux/vfio.h | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/include/linux/vfio.h b/include/linux/vfio.h
index edf9b2c..0a05d57 100644
--- a/include/linux/vfio.h
+++ b/include/linux/vfio.h
@@ -150,7 +150,7 @@ extern int vfio_set_irqs_validate_and_prepare(struct vfio_irq_set *hdr,
 					      size_t *data_size);
 
 struct pci_dev;
-#ifdef CONFIG_EEH
+#ifdef CONFIG_VFIO_SPAPR_EEH
 extern void vfio_spapr_pci_eeh_open(struct pci_dev *pdev);
 extern void vfio_spapr_pci_eeh_release(struct pci_dev *pdev);
 extern long vfio_spapr_iommu_eeh_ioctl(struct iommu_group *group,
@@ -171,7 +171,7 @@ static inline long vfio_spapr_iommu_eeh_ioctl(struct iommu_group *group,
 {
 	return -ENOTTY;
 }
-#endif /* CONFIG_EEH */
+#endif /* CONFIG_VFIO_SPAPR_EEH */
 
 /*
  * IRQfd - generic
```

**Comment by mopsfelder** [comment]
@mpe Thank you for reviewing. I sent it out:

https://www.spinics.net/lists/kernel/msg2525671.html

**Comment by mopsfelder** [comment]
@mpe As we've investigated, the http://kisskb.ellerman.id.au/kisskb/buildresult/13052890/ is due an issue with ld (binutils). This is the upstream bug I've filled to help us tracking the segfault on ld:

https://sourceware.org/bugzilla/show_bug.cgi?id=22431

**Comment by mpe** [comment]
All solved! Thanks @mopsfelder :beer: !
