### ISSUE TITLE
Should we add 16G page support for powernv?

### ISSUE THREAD

**Issue by mpe** [linuxppc/linux#98]
Currently there is no way to allocate gigantic (16G) pages on powernv. On pseries it is done via the device tree because the HV tells us that we can use them. We have code which is BookE only which does it using the command line, we could make that also work on powernv.

**Comment by bsingharora** [comment]
I'd be interested in helping, but I am not sure if I can pick it up right away

**Comment by kvaneesh** [comment]
https://lkml.kernel.org/r/20170728050127.28338-1-aneesh.kumar@linux.vnet.ibm.com merged

**Comment by mpe** [comment]
Implemented as of e24a1307ba1f, thanks @kvaneesh :cake:
